### ISSUE TITLE
User Profile Bug

### ISSUE THREAD

**Issue by nouphet** [XoopsX/legacy#25]
<en>
Adding new user on Admin Panel is fail.
Fix the bug.

<ja>
プロフィールモジュールで項目を追加している場合、管理画面からユーザを追加しようとするとユーザの追加が正常にできないのを修正。

**Comment by hamaco** [comment]
あれ? まるで修正したかのように書かれてるけど、もしかしてこれPull RequestじゃなくてIssueなのか?

**Comment by nouphet** [comment]
このIssueに対してPull Request するつもりだったんだけど、Pull Request したら #26 として入ってしまいました。

**Comment by nao-pon** [comment]
ということで、こちらは閉じておきますね。
