### ISSUE TITLE
安定版ダウンロードで、corepack_20130605がダウンロードされる

### ISSUE THREAD

**Issue by RyujiAMANO** [XoopsX/legacy#58]
http://www.xoopscube.net/modules/xpwiki/#wa5e9b19
にある「安定版ダウンロード」のリンク先
https://github.com/XoopsX/legacy/zipball/stable
でダウンロードされるのが、corepack_20130810でなく一つ前のcorepack_20130605になってるようです。

**Comment by nao-pon** [comment]
Ryuji さん、ありがとうございます。タグを打ち忘れていまして、ダウンロードされるファイル名のみが 20130605 になっていました。（中身は20130810）

Tag を打っておきました。

また、ダウンロードされるファイル名が紛らわしいので、ダウンロード先 URL を https://github.com/XoopsX/legacy/archive/stable.zip に変更しておきました。

ちなみに過去のバージョンは https://github.com/XoopsX/legacy/releases から取得できます。

**Comment by RyujiAMANO** [comment]
おつかれさまですー
20130810がダウンロードできることを確認しましたー
