### ISSUE TITLE
XCL が送信するメールの送信元アドレスをしていできるように

### ISSUE THREAD

**Issue by nao-pon** [XoopsX/legacy#73]
ユーザー登録時、パスワード紛失時、イベント通知時などで送信されるメールアドレスが、管理者メールアドレスに固定されているので、送信専用アドレスなどを持つ場合には、それを指定できるようにしたい。

**Comment by bluemooninc** [comment]
多分、legacyモジュールに変更掛かりますね。ここをメインのリポジトリとりと考えて良いですか？

**Comment by nao-pon** [comment]
メインという定義は人それぞれだと思います。

これまでは XoopsX で変更を加えて、PullRequest を送って xoopscube に取り込んでもらっていましたが、現状では
xoopscube が停止している以上、セキュリティー修正やバグ修正以外は XoopsX 側が独自に進むことになると思います。
2015/03/30 20:30 "Yoshi Sakai" notifications@github.com:

**Comment by bluemooninc** [comment]
了解しました。自分も時間が取れる時にはコミットします。
2015/03/30 20:45 "Naoki Sawada" notifications@github.com:
