### ISSUE TITLE
XOOPS_DB_TYPE に mysqli をセットすると文字化けする

### ISSUE THREAD

**Issue by kujiy** [XoopsX/legacy#76]
[こちら](https://github.com/XoopsX/legacy/pull/69)を参考に以下を試したところ文字コードが合っていないようで文字化けしました。

`define('XOOPS_DB_TYPE', 'mysqli');`

適当に `mysqlidatabase.php` に以下を追加したら直ったのですが、

``` php
<?php
$this->setCharset("utf8");
```

これをコアハックせずに正しく対応するにはどうしたらいいでしょうか。

また、これはxoops内部が他の文字コード（euc-jp？) で動いているということでしょうか。utf-8にデフォルトで対応する予定はあるでしょうか。

**Comment by nao-pon** [comment]
@kujiy MySQL の文字エンコーディングを設定する html/modules/legacy/language/ja_utf8/charset_mysqli.php が抜けていましたので修正しました。

ありがとうございます。  :+1:

**Comment by kujiy** [comment]
ありがとうございました :+1:
